[[vamana_static_build]]
__version__ = 'v0.0.1'
build_type = 'uncompressed'
description = 'test-dataset'
data = 'data/test_dataset/data_f32.fvecs'
data_type = 'float32'
queries = 'data/test_dataset/queries_f32.fvecs'
query_type = 'float32'
groundtruth = 'data/test_dataset/groundtruth_euclidean.ivecs'
distance = 'L2'
ndims = 'dynamic'
num_threads = 8
search_window_sizes = [10, 20]

    [vamana_static_build.build_parameters]
    __version__ = 'v0.0.0'
    alpha = 1.2
    graph_max_degree = 64
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    use_full_search_history = true
    window_size = 100

    [vamana_static_build.search_parameters]
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.8, 0.85, 0.9 ]
